language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install --dev --prefer-source

script:
  - find ./src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  - vendor/bin/phpunit
  - vendor/bin/phpspec run -f pretty --no-interaction
  - ./vendor/bin/phpcs --standard=./phpcs-ruleset.xml .

# Enable Travis containers.
sudo: false
